language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
    secure: ZEpvv9agGkxoklZCmfqIdh0luipiQEihjwAnAE2GPOvqi89Si8Dm4imKxIa1/GNrYSwa/YaVcPHpVeoSmMO64tp92/rThHB1SBlWAS2cpRRllJKj5eNt5OArSaWGKitePgNJkwdLzMNtSFpLITke6TDvUlKTaN/z6MSh+pVGH98=
